### PR TITLE
[Docs] Document most scheduling functions.

### PR DESCRIPTION
**Pull request by jku20**
## Description ##
Documents the functions exposed by the scheduling language and by the dsl. 

### Problems ###
Documentation (or the lack thereof).

### Proposed Solutions ###
Added documentation. 

### Examples ###
N/A

## Checklist ##

- [x] PR's title starts with a category (e.g. [Bugfix], [IR], [Builder], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage (It would be better to provide ~2 different test cases to test the robustness of your code)
- [x] Code is well-documented

### CODE REVIEW

**Comment by chhzh123** [comment]
Hi @jku20, this is really helpful! Could you follow this guide to format your files before I take a closer look?
https://cornell-zhang.github.io/allo/developer/index.html#id1

**Comment by jku20** [comment]
Of course! I'll un-draft this PR and request a review when it is ready (it should pass all the CI formatting, and non-formatting for that matter, checks then too). At current, this is just the quick, lightly edited copy-past of the scheduling functions.

**Comment by jku20** [comment]
I haven't got around to doing the functions in the dsl, but here is reasonably usable, though not really complete, documentation of the scheduling functions and types.

**Comment by jku20** [comment]
The above PR should be functional (whatever that means for docs). Do double check it though as I'm not 100% confident on everything. 

Especially check the documentation of `to`. I couldn't figure out what `axis` was doing (or what `depth=-1` means) so I just copied the docs from the tablegen of the op the thing schedule gets lowered to.

**Pull request merged**
